Documentation:
    Enabled: false

Metrics/AbcSize:
  Max: 26
  Exclude:
    - lib/splitclient-rb/telemetry/memory/memory_synchronizer.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/splitclient-rb/telemetry/memory/memory_synchronizer.rb
    - lib/splitclient-rb/engine/sync_manager.rb

Metrics/ClassLength:
  Max: 150
  Exclude:
    - lib/splitclient-rb/telemetry/memory/memory_synchronizer.rb

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/ParameterLists:
  Max: 8
  Exclude:
    - lib/splitclient-rb/engine/sync_manager.rb

Metrics/LineLength:
  Max: 135
  Exclude:
    - spec/sse/**/*
    - spec/integrations/**/*
    - spec/engine/sync_manager_spec.rb
    - spec/engine/auth_api_client_spec.rb
    - spec/telemetry/synchronizer_spec.rb
    - spec/splitclient/split_config_spec.rb
    - spec/engine/push_manager_spec.rb
    - spec/cache/senders/impressions_sender_adapter_spec.rb

Style/BracesAroundHashParameters:
  Exclude:
    - spec/integrations/push_client_spec.rb
    - spec/engine/synchronizer_spec.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - splitclient-rb.gemspec

Naming/FileName:
  Exclude:
    - splitclient-rb.gemspec

AllCops:
  TargetRubyVersion: 2.3.6
  Exclude:
    - gemfiles/* # excluded as appraisal generates them with errors
    - lib/*
    - lib/murmurhash/**/*
    - lib/splitclient-rb/*
    - lib/splitclient-rb/cache/**/*
    - lib/splitclient-rb/clients/**/*
    - lib/splitclient-rb/managers/**/*
    - lib/splitclient-rb/engine/api/**/*
    - lib/splitclient-rb/engine/evaluator/**/*
    - lib/splitclient-rb/engine/metrics/**/*
    - lib/splitclient-rb/engine/models/**/*
    - lib/splitclient-rb/engine/parser/**/*
    - spec/telemetry/synchronizer_spec.rb
    - lib/splitclient-rb/engine/synchronizer.rb
    - tmp/**/*
    - lib/splitclient-rb/sse/event_source/client.rb
